# Generated by Django 5.2.4 on 2025-08-13 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbag', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Borrowingtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='date borrowed')),
                ('end', models.DateTimeField(verbose_name='date returned')),
                ('member', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bags.borrowingtime')),
            ],
        ),
    ]
