# Generated by Django 5.2.4 on 2025-08-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='employee_name',
            field=models.CharField(default='boo', max_length=100),
            preserve_default=False,
        ),
    ]
