# Generated by Django 5.2.4 on 2025-08-20 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bags', '0002_employees_employee_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Bags',
            new_name='Bag',
        ),
        migrations.AddField(
            model_name='borrowingtime',
            name='bag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bags.bag'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='borrowingtime',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bags.employee'),
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
    ]
