# Generated by Django 5.2.4 on 2025-08-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bags', '0004_remove_employee_employee_name_employee_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowingtime',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date returned'),
        ),
    ]
