# Generated by Django 5.2.4 on 2025-08-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bags', '0005_alter_borrowingtime_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowingtime',
            name='end',
            field=models.DateTimeField(blank=' ', null=' ', verbose_name='date returned'),
        ),
    ]
