# Generated by Django 4.2.25 on 2025-10-13 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bags', '0006_alter_borrowingtime_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowingtime',
            name='contents',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrowingtime',
            name='bag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowingtimes', to='bags.bag'),
        ),
    ]
