# Generated by Django 4.2.25 on 2025-11-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bags', '0007_borrowingtime_contents_alter_borrowingtime_bag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowingtime',
            name='contents',
        ),
        migrations.AddField(
            model_name='bag',
            name='contents',
            field=models.TextField(blank=True, null=True),
        ),
    ]
