# Generated by Django 4.2.25 on 2025-11-24 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bags', '0009_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowingtime',
            name='tagg',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='taggage', to='bags.tags'),
            preserve_default=False,
        ),
    ]
