# Generated by Django 4.2.25 on 2025-11-24 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bags', '0010_borrowingtime_tagg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowingtime',
            name='tagg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowingtimes', to='bags.tags'),
        ),
    ]
