# Generated by Django 4.2.25 on 2025-12-01 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bags', '0011_alter_borrowingtime_tagg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowingtime',
            name='tagg',
        ),
        migrations.AddField(
            model_name='bag',
            name='tagg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Bag', to='bags.tags'),
        ),
        migrations.AlterField(
            model_name='borrowingtime',
            name='bag',
            field=models.ForeignKey(blank=' ', null=' ', on_delete=django.db.models.deletion.CASCADE, related_name='borrowingtimes', to='bags.bag'),
        ),
    ]
