# Generated by Django 4.2.25 on 2025-12-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bags', '0012_remove_borrowingtime_tagg_bag_tagg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='contents',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
    ]
